feat: deploy with docker
cryptape/cita-ide pull request #41
Opened 2020-06-08 08:11 UTC by travis-joe

2020-06-09 02:09 UTC, miaojuncn approved these changes

2020-06-12 04:43 UTC, rainchen commented on docker-compose.yaml
> +version: '3'
file name should be docker-compose.yml

2020-06-12 04:44 UTC, rainchen commented on docker-compose.yaml
> +      - 9000:9000
should keep a newline at end of file

2020-06-12 04:44 UTC, rainchen commented on nginx.conf
> +}
should keep a newline at end of file

2020-06-12 04:46 UTC, rainchen commented on nginx.conf
> +server {
should move this  to a `docker/nginx/` dir, same as other projects

2020-06-12 04:50 UTC, rainchen commented on Dockerfile
> +COPY . .
should add COPY package.json and put COPY . . after npm build command, check the best practice for build docker image for a nodejs project

2020-06-12 04:51 UTC, rainchen requested changes
please update

2020-06-12 06:09 UTC, rainchen approved these changes

2020-06-12 06:09 UTC, merged